enum Endpoints {
  getUserItems,
  searchProductByCategory,
  getCategories,
  customerDetails,
  login,
  register,
  getHomeItems,
  getCompanyDetails,
  getCartList,
  getCustomerList,
  getOutLet,
  getProfile,
  updateBusinesDetails,
  getCustomerDetails,
  updateProfile,
  updatePostalAddress,
  getUserOrders,
  getLinkPost,
  getAppUserguide,
  updateUserInventry,
}

const Map<Endpoints, String> endpointRawValues = {
  // AUTHENTICATION
  Endpoints.login: "/apis/ac/loginNew",
  Endpoints.register: "/apis/ac/customer/registration",
  Endpoints.getHomeItems: "/apis/get_home_items_v6",
  Endpoints.getCompanyDetails: "/apis/getCompanydetails",
  Endpoints.getCartList: "/apis/cart_list_v6",
  Endpoints.getCustomerList: "/apis/ac/customerList",
  Endpoints.getOutLet: "/apis/get_outlets",
  Endpoints.getProfile: "/apis/get_profile",
  Endpoints.getCustomerDetails: "/apis/ac/customerDetails",
  Endpoints.updateBusinesDetails: "/apis/update_business_detail",
  Endpoints.updateProfile: "/apis/edit_profile_contact_detail",
  Endpoints.updatePostalAddress: "/apis/update_postal_detail",
  Endpoints.getUserOrders: "/apis/get_user_order_v3",
  Endpoints.getLinkPost: "/apis/linksPost",
  Endpoints.getAppUserguide: "/apis/app_cms",
  Endpoints.customerDetails: "/apis/ac/customerDetails",
  Endpoints.getCategories: "/apis/GetCategories_v3_4",
  Endpoints.searchProductByCategory: "/apis/search_product_bycategory_v3_4",
  Endpoints.getUserItems: "/apis/get_user_items_v3_4",
  Endpoints.updateUserInventry: "/apis/update_user_inventory_v6",
};
